---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
- config/
- node_modules/
- test/
